# Data validation and pre-processing technique

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#import library packages
import pandas as p
import numpy as n

In [3]:
#Load given dataset
data = p.read_csv("Bitcoin.csv")

Before drop the given dataset

In [4]:
data.head()

Date  BTC price [USD]  n-transactions  fee [USD]  btc search trends  \
0  2014-01-02           749.27         54770.0       0.18                  8   
1  2014-01-03           781.23         60980.0        NaN                  8   
2  2014-01-04           807.39         52052.0        NaN                  8   
3  2014-01-05           828.74         58662.0       0.38                  8   
4  2014-01-06           904.98         67358.0        NaN                  8   

   Gold price[USD]  SP500 close index  Oil WTI price[USD]  \
0           1225.0            1831.98               95.14   
1           1238.4            1831.37               93.66   
2              NaN                NaN                 NaN   
3              NaN                NaN                 NaN   
4           1237.8            1826.77               93.12   

   M2(Not seasonally adjusted)[1e+09 USD]  
0                                 11089.3  
1                                 11089.3  
2                                 11089.3  
3                                 11089.3  
4                                 11089.3

In [5]:
data.shape

(2310, 9)

After drop the given dataset

In [6]:
df=data.dropna()
df.head()

Date  BTC price [USD]  n-transactions  fee [USD]  btc search trends  \
0   2014-01-02           749.27         54770.0       0.18                  8   
6   2014-01-08           790.00         61439.0       0.18                  8   
12  2014-01-14           823.00         57378.0       0.22                  8   
15  2014-01-17           817.15         59026.0       0.19                  8   
21  2014-01-23           819.62         63576.0       0.19                  8   

    Gold price[USD]  SP500 close index  Oil WTI price[USD]  \
0            1225.0            1831.98               95.14   
6            1225.3            1837.49               91.90   
12           1245.2            1838.88               92.15   
15           1251.7            1838.70               93.96   
21           1262.6            1828.46               97.23   

    M2(Not seasonally adjusted)[1e+09 USD]  
0                                  11089.3  
6                                  11089.3  
12                                 11089.3  
15                                 11089.3  
21                                 11089.3

In [7]:
df.shape

(1002, 9)

In [8]:
#show columns
df.columns

Index(['Date', 'BTC price [USD]', 'n-transactions', 'fee [USD]',
       'btc search trends', 'Gold price[USD]', 'SP500 close index',
       'Oil WTI price[USD]', 'M2(Not seasonally adjusted)[1e+09 USD]'],
      dtype='object')

In [9]:
df.rename(columns={"BTC price [USD]":"BTC_price_USD"},inplace=True)
df.rename(columns={"n-transactions":"n_transactions"},inplace=True)
df.rename(columns={"fee [USD]":"fee_USD"},inplace=True)
df.rename(columns={"btc search trends":"btc_search_trends"},inplace=True)
df.rename(columns={"Gold price[USD]":"Gold_price_USD"},inplace=True)
df.rename(columns={"SP500 close index":"SP500_close_index"},inplace=True)
df.rename(columns={"Oil WTI price[USD]":"Oil_WTI_price_USD"},inplace=True)
df.rename(columns={"M2(Not seasonally adjusted)[1e+09 USD]":"M2_money_supply_USA"},inplace=True)

In [10]:
df.columns

Index(['Date', 'BTC_price_USD', 'n_transactions', 'fee_USD',
       'btc_search_trends', 'Gold_price_USD', 'SP500_close_index',
       'Oil_WTI_price_USD', 'M2_money_supply_USA'],
      dtype='object')

In [11]:
df['n_transactions'].unique()

array([ 54770.,  61439.,  57378., ..., 311217., 323475., 331401.])

In [12]:
df['fee_USD'].unique()

array([1.800e-01, 2.200e-01, 1.900e-01, 1.700e-01, 1.600e-01, 1.400e-01,
       1.300e-01, 1.100e-01, 1.500e-01, 1.200e-01, 9.000e-02, 1.000e-01,
       8.000e-02, 7.000e-02, 6.000e-02, 5.000e-02, 4.000e-02, 3.000e-02,
       2.100e-01, 2.000e-01, 2.700e-01, 2.300e-01, 3.000e-01, 2.500e-01,
       2.800e-01, 2.900e-01, 3.100e-01, 3.300e-01, 4.200e-01, 3.600e-01,
       4.300e-01, 5.000e-01, 5.500e-01, 4.500e-01, 6.100e-01, 7.200e-01,
       6.800e-01, 8.300e-01, 9.800e-01, 9.200e-01, 1.000e+00, 8.500e-01,
       9.400e-01, 7.900e-01, 8.400e-01, 7.300e-01, 9.000e-01, 8.800e-01,
       1.040e+00, 1.180e+00, 1.540e+00, 1.410e+00, 1.740e+00, 2.740e+00,
       2.800e+00, 3.370e+00, 4.270e+00, 5.560e+00, 4.460e+00, 3.380e+00,
       3.660e+00, 3.830e+00, 4.500e+00, 3.540e+00, 3.520e+00, 3.390e+00,
       3.470e+00, 3.730e+00, 3.360e+00, 2.450e+00, 2.790e+00, 2.510e+00,
       2.000e+00, 1.830e+00, 2.030e+00, 2.020e+00, 2.140e+00, 1.770e+00,
       1.940e+00, 2.530e+00, 1.900e+00, 1.800e+00, 

In [13]:
df["btc_search_trends"].unique()

array([  8,   9,   6,   4,   3,   2,   5,   7,  15,  14,  12,  20,  21,
        22,  44, 100,  54,  40,  18,  13,  10,  17,  11,  19,  16],
      dtype=int64)

In [14]:
df["Gold_price_USD"].unique()

array([1225. , 1225.3, 1245.2, 1251.7, 1262.6, 1262.2, 1263.3, 1274.8,
       1300.4, 1320.6, 1343. , 1321.4, 1350.1, 1351.7, 1370.3, 1359. ,
       1336. , 1311.2, 1294.7, 1283.4, 1284.4, 1305.5, 1300. , 1288. ,
       1290.5, 1295.6, 1308.3, 1287.3, 1293.5, 1265.4, 1245.6, 1243.7,
       1253. , 1260.8, 1271.7, 1316.2, 1318. , 1316.1, 1484.8, 1471.4,
       1492.9, 1460.7, 1472.1, 1460.3, 1456.7, 1451.1, 1441.9, 1467.3,
       1467.9, 1449. , 1434.1, 1433.1, 1443.8, 1425.5, 1404.6, 1387.8,
       1391.3, 1383.4, 1374.9, 1366.7, 1346.9, 1360.7, 1358.8, 1361.3,
       1371.8, 1355. , 1349.2, 1290.3, 1291. , 1281.3, 1281.4, 1313.4,
       1315.2, 1291.2, 1332.5, 1324.2, 1345.5, 1302. , 1305.6, 1289.7,
       1295.4, 1322.2, 1317.4, 1333.2, 1352.8, 1378.4, 1379.7, 1349.6,
       1347.4, 1336.9, 1301.2, 1291.9, 1285.2, 1280.7, 1288.1, 1282.6,
       1240.1, 1230.9, 1231.3, 1241.5, 1269.3, 1276.2, 1280.4, 1275.3,
       1269.8, 1265. , 1256.7, 1248.1, 1261. , 1260.5, 1294.2, 1281.7,
      

In [15]:
df["SP500_close_index"].unique()

array([1831.98, 1837.49, 1838.88, 1838.7 , 1828.46, 1774.2 , 1755.2 ,
       1797.02, 1799.84, 1829.83, 1828.75, 1845.12, 1859.45, 1845.73,
       1877.03, 1868.2 , 1872.25, 1866.52, 1857.44, 1849.04, 1872.34,
       1888.77, 1872.18, 1842.98, 1871.89, 1878.61, 1883.95, 1867.72,
       1878.48, 1896.65, 1870.85, 1888.03, 1911.91, 1923.57, 1924.97,
       1940.46, 1943.89, 1941.99, 1962.87, 1962.61, 1957.22, 1974.62,
       1963.71, 1967.57, 1977.1 , 1958.12, 1987.01, 1969.95, 1925.15,
       1938.99, 1909.57, 1946.72, 1981.6 , 1988.4 , 1997.92, 1996.74,
       2000.72, 1988.44, 1985.54, 1984.13, 2011.36, 1998.3 , 1972.29,
       1967.9 , 1964.82, 1928.21, 1862.49, 1941.28, 1964.58, 1982.3 ,
       2012.1 , 2031.92, 2038.26, 2039.33, 2048.72, 2067.03, 2067.56,
       2053.44, 2071.92, 2026.14, 1972.74, 2070.65, 2078.54, 2058.9 ,
       2002.61, 2044.81, 2028.26, 1992.67, 2032.12, 2029.55, 1994.99,
       2020.85, 2062.52, 2068.53, 2100.34, 2110.3 , 2109.66, 2110.74,
       2098.53, 2044

In [16]:
df["Oil_WTI_price_USD"].unique()

array([ 95.14,  91.9 ,  92.15,  93.96,  97.23,  97.34,  97.24,  99.98,
       100.12, 100.27, 103.46, 102.2 , 102.88, 105.34, 101.82,  98.29,
       100.08,  99.97, 100.05, 101.25, 101.57, 100.29, 103.55, 103.7 ,
       104.35, 100.07,  99.81, 100.32, 100.89, 101.74, 104.31, 104.78,
       103.4 , 103.07, 103.17, 105.04, 106.95, 107.95, 106.83, 106.49,
       105.18, 104.06, 101.48, 101.73, 103.84, 103.81, 104.91,  97.86,
        98.26,  97.57,  94.35,  93.61,  95.39,  96.44,  95.5 ,  92.73,
        92.18,  92.86,  93.07,  93.6 ,  91.17,  89.76,  90.33,  85.76,
        81.82,  83.25,  81.27,  82.25,  77.15,  78.71,  77.43,  74.13,
        74.55,  74.04,  65.94,  68.98,  66.73,  60.99,  55.97,  56.91,
        55.25,  53.45,  47.98,  48.35,  46.06,  46.37,  47.85,  45.84,
        47.79,  49.25,  50.48,  48.8 ,  53.56,  49.95,  49.56,  47.65,
        51.53,  48.42,  44.88,  43.93,  44.02,  48.75,  50.12,  53.95,
        51.63,  51.95,  56.69,  56.17,  57.05,  59.1 ,  58.92,  58.99,
      

In [17]:
df["M2_money_supply_USA"].unique()

array([11089.3, 11140.9, 11266.3, 11319.5, 11262.8, 11324.8, 11379.9,
       11411. , 11459. , 11526.8, 11602.8, 11747.9, 11746.9, 11835.1,
       11944.9, 11992.7, 11896.1, 11950.7, 12001.3, 12058.7, 12126.3,
       12159.8, 12286.2, 12416.1, 12467.2, 12506.1, 12673.9, 12767.5,
       12697.4, 12777.9, 12839.3, 12937. , 13007.7, 13072.4, 13185.5,
       13293.8, 13275.7, 13299.5, 13485.6, 13558.5, 13467.3, 13515.2,
       13577.3, 13646.1, 13696.5, 13741.6, 13810.9, 13936.6, 13856.2,
       13842.2, 14024. , 14068. , 13988.9, 14080.6, 14115.1, 14171.6,
       14207.2, 14209.7, 14263.2, 14456.5, 14433.6, 14411.4, 14582.9,
       14633.9, 14584.1, 14743.5, 14822.7, 14903.9, 14994.9, 15121. ,
       15266.6, 15418. , 15420.9, 15457.2, 16181. , 17269.8])

In [18]:
#To describe the dataframe
df.describe()

BTC_price_USD  n_transactions      fee_USD  btc_search_trends  \
count    1002.000000     1002.000000  1002.000000        1002.000000   
mean     5352.851926   254421.630739     2.230409          15.163673   
std      3892.224190    88589.954049     5.568724          15.852566   
min       172.000000    54142.000000     0.030000           2.000000   
25%       884.052500   207520.500000     0.230000           6.000000   
50%      5895.335000   267637.500000     0.700000          13.000000   
75%      8171.610000   322157.500000     1.767500          17.750000   
max     18911.790000   490644.000000    54.790000         100.000000   

       Gold_price_USD  SP500_close_index  Oil_WTI_price_USD  \
count     1002.000000        1002.000000        1002.000000   
mean      1369.540319        2584.999880          57.670948   
std        114.562397         383.177031          15.852663   
min       1097.700000        1755.200000         -36.980000   
25%       1293.550000        2265.067500          49.545000   
50%       1345.650000        2672.275000          56.285000   
75%       1420.275000        2864.117500          63.950000   
max       1768.900000        3386.150000         107.950000   

       M2_money_supply_USA  
count          1002.000000  
mean          13867.278842  
std            1274.266180  
min           11089.300000  
25%           13293.800000  
50%           14024.000000  
75%           14584.100000  
max           17269.800000

In [19]:
#Checking datatype and information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1002 entries, 0 to 2309
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Date                 1002 non-null   object 
 1   BTC_price_USD        1002 non-null   float64
 2   n_transactions       1002 non-null   float64
 3   fee_USD              1002 non-null   float64
 4   btc_search_trends    1002 non-null   int64  
 5   Gold_price_USD       1002 non-null   float64
 6   SP500_close_index    1002 non-null   float64
 7   Oil_WTI_price_USD    1002 non-null   float64
 8   M2_money_supply_USA  1002 non-null   float64
dtypes: float64(7), int64(1), object(1)
memory usage: 78.3+ KB


Checking duplicate values of dataframe

In [20]:
#Checking for duplicate data
df.duplicated()

0       False
6       False
12      False
15      False
21      False
        ...  
2303    False
2304    False
2307    False
2308    False
2309    False
Length: 1002, dtype: bool

In [21]:
#find sum of duplicate data
sum(df.duplicated())

0

In [22]:
#Checking sum of missing values
df.isnull().sum()

Date                   0
BTC_price_USD          0
n_transactions         0
fee_USD                0
btc_search_trends      0
Gold_price_USD         0
SP500_close_index      0
Oil_WTI_price_USD      0
M2_money_supply_USA    0
dtype: int64

In [23]:
df.columns

Index(['Date', 'BTC_price_USD', 'n_transactions', 'fee_USD',
       'btc_search_trends', 'Gold_price_USD', 'SP500_close_index',
       'Oil_WTI_price_USD', 'M2_money_supply_USA'],
      dtype='object')

In [24]:
df['BTC_price_USD'].value_counts()

569.01     2
2600.00    2
376.03     2
4032.25    1
3246.64    1
          ..
4612.12    1
4613.84    1
4232.93    1
4198.59    1
7765.33    1
Name: BTC_price_USD, Length: 999, dtype: int64

In [25]:
print("Minimum BTC_price_USD value is:", df.BTC_price_USD.min())
print("Maximum BTC_price_USD value is:", df.BTC_price_USD.max())

Minimum BTC_price_USD value is: 172.0
Maximum BTC_price_USD value is: 18911.79


In [26]:
p.Categorical(df['btc_search_trends']).describe()

counts     freqs
categories                  
2               36  0.035928
3              158  0.157685
4               27  0.026946
5                8  0.007984
6               26  0.025948
7                8  0.007984
8               27  0.026946
9                7  0.006986
10              84  0.083832
11              19  0.018962
12              82  0.081836
13             143  0.142715
14              55  0.054890
15              29  0.028942
16              20  0.019960
17              22  0.021956
18              42  0.041916
19              22  0.021956
20              43  0.042914
21              20  0.019960
22              43  0.042914
40              19  0.018962
44              21  0.020958
54              21  0.020958
100             20  0.019960

In [27]:
p.Categorical(df['BTC_price_USD']).describe()

counts     freqs
categories                  
172.0            1  0.000998
210.71           1  0.000998
220.36           1  0.000998
222.13           1  0.000998
222.55           1  0.000998
...            ...       ...
16860.88         1  0.000998
16916.8          1  0.000998
17382.94         1  0.000998
18905.26         1  0.000998
18911.79         1  0.000998

[999 rows x 2 columns]

In [28]:
df.corr()

BTC_price_USD  n_transactions   fee_USD  \
BTC_price_USD             1.000000        0.596925  0.517846   
n_transactions            0.596925        1.000000  0.273090   
fee_USD                   0.517846        0.273090  1.000000   
btc_search_trends         0.677435        0.384363  0.834244   
Gold_price_USD            0.523268        0.376860  0.011837   
SP500_close_index         0.792344        0.720957  0.116217   
Oil_WTI_price_USD        -0.004852       -0.420285 -0.000592   
M2_money_supply_USA       0.678480        0.771463  0.054859   

                     btc_search_trends  Gold_price_USD  SP500_close_index  \
BTC_price_USD                 0.677435        0.523268           0.792344   
n_transactions                0.384363        0.376860           0.720957   
fee_USD                       0.834244        0.011837           0.116217   
btc_search_trends             1.000000        0.142426           0.289335   
Gold_price_USD                0.142426        1.000000           0.557169   
SP500_close_index             0.289335        0.557169           1.000000   
Oil_WTI_price_USD            -0.029324       -0.196017          -0.104263   
M2_money_supply_USA           0.237495        0.676179           0.864312   

                     Oil_WTI_price_USD  M2_money_supply_USA  
BTC_price_USD                -0.004852             0.678480  
n_transactions               -0.420285             0.771463  
fee_USD                      -0.000592             0.054859  
btc_search_trends            -0.029324             0.237495  
Gold_price_USD               -0.196017             0.676179  
SP500_close_index            -0.104263             0.864312  
Oil_WTI_price_USD             1.000000            -0.439634  
M2_money_supply_USA          -0.439634             1.000000

Before Pre-Processing:

In [29]:
df.head()

Date  BTC_price_USD  n_transactions  fee_USD  btc_search_trends  \
0   2014-01-02         749.27         54770.0     0.18                  8   
6   2014-01-08         790.00         61439.0     0.18                  8   
12  2014-01-14         823.00         57378.0     0.22                  8   
15  2014-01-17         817.15         59026.0     0.19                  8   
21  2014-01-23         819.62         63576.0     0.19                  8   

    Gold_price_USD  SP500_close_index  Oil_WTI_price_USD  M2_money_supply_USA  
0           1225.0            1831.98              95.14              11089.3  
6           1225.3            1837.49              91.90              11089.3  
12          1245.2            1838.88              92.15              11089.3  
15          1251.7            1838.70              93.96              11089.3  
21          1262.6            1828.46              97.23              11089.3

After Pre-Processing:

In [30]:
df.columns

Index(['Date', 'BTC_price_USD', 'n_transactions', 'fee_USD',
       'btc_search_trends', 'Gold_price_USD', 'SP500_close_index',
       'Oil_WTI_price_USD', 'M2_money_supply_USA'],
      dtype='object')

In [31]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Date', 'BTC_price_USD', 'n_transactions', 'fee_USD',
       'btc_search_trends', 'Gold_price_USD', 'SP500_close_index',
       'Oil_WTI_price_USD', 'M2_money_supply_USA']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(str)


In [32]:
df.head(20)


Date BTC_price_USD n_transactions fee_USD btc_search_trends Gold_price_USD  \
0     0           233              1      15                 6             45   
6     1           240             10      15                 6             46   
12    2           246              2      19                 6             68   
15    3           244              5      16                 6             78   
21    4           245             14      16                 6            110   
27    5           239              7      14                 6            109   
33    6           243             35      13                 7             78   
36    7           236             42      11                 7            112   
39    8           224             23      10                 7            137   
42    9           216             28      11                 7            231   
48   10           202             40      10                 7            311   
54   11           160             65       8                 7            398   
57   12           174             41       8                 7            314   
60   13           163             67      11                 4            432   
63   14           220             43      10                 4            439   
69   15           206             57      10                 4            500   
75   16           201              0       8                 4            463   
78   17           179             49      12                 4            371   
81   18           161             44       9                 4            269   
84   19           171             45       6                 4            216   

   SP500_close_index Oil_WTI_price_USD M2_money_supply_USA  
0                  7               839                   0  
6                  8               829                   0  
12                10               830                   0  
15                 9               837                   0  
21                 4               843                   0  
27                 1               845                   0  
33                 0               844                   1  
36                 2               852                   1  
39                 3               856                   1  
42                 6               857                   1  
48                 5               872                   1  
54                12               867                   1  
57                17               868                   1  
60                13               884                   3  
63                28               866                   3  
69                22               849                   3  
75                26               855                   3  
78                20               851                   3  
81                16               853                   3  
84                14               861                   3